### ISSUE TITLE
Tag being added to above folder not just files created in the folder

### ISSUE THREAD

**Issue by stondino00** [nextcloud/files_automatedtagging#799] opened 2023-09-29 19:08 UTC
So for some reason when we apply a tag it's applying to the folder as well when files are added to that folder.

So we want files in a folder to be deleted with the retention app but as soon as we add files to this folder, they DO get the tag we created BUT the folder gets added the tag as well.

**Comment by nickvergessen** [comment] 2023-09-29 19:15
Mostlikely your rule is "Item is changed".
A folder changes, when an item inside is added, deleted or modified.

Duplicate of https://github.com/nextcloud/files_automatedtagging/issues/795

**Closed by nickvergessen** 2023-09-29 19:15 UTC
