### ISSUE TITLE
No tagging within group folders

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/files_automatedtagging#76] opened 2019-05-20 13:10 UTC
This app doesn't seem to work with group folders on Nextcloud 16.0.1
### Steps to reproduce
1. Install Group folders app (4.0.0.)
2. Create some group folder
3. Assign a (hidden) tag to a folder within group folder, e.g. "folder documents".
4. Create a rule: Assign tag "document" when file system tag is "folder documents".

### Expected behaviour
When creating a new file in the documents folder, the tag "document" should be applied automatically.

### Actual behaviour
No tags are assigned,

### Server configuration
**Operating system**: Ubuntu Server 18.04

**Web server:** nginx

**Database:** PostgreSQL

**PHP version:** 7.2

**Nextcloud version:** 16.0.1

**Where did you install Nextcloud from:** Updated from NC 15

**Are you using encryption:** no

#### Nextcloud log (data/owncloud.log)
There are no log entries created.

**Comment by DecaTec** [comment] 2019-05-20 16:51
OK, this isn't related to PostgreSQL.
Fresh install of NC 16.0.1 and apps files automated tagging and group folders: Same result, no tagging of files inside group folders.

**Comment by nickvergessen** [comment] 2019-06-21 12:50
Duplicate of #46

**Closed by nickvergessen** 2019-06-21 12:50 UTC

**Comment by DecaTec** [comment] 2019-06-21 13:28
However, this is still not working :disappointed:

**Comment by Innky-Joe** [comment] 2024-01-11 11:20
![Untitled](https://github.com/nextcloud/files_automatedtagging/assets/156313232/a6e98ece-3b80-4a39-9eb2-0dc4aaf75493)

I am running Group folders by Robin Appelman AGPL-licensed 16.0.1 on NC V.28 and add advanced permission rule not showing, can anyone help me out?

Related resources
Anything shared with the same group of people will show up here

**Comment by blizzz** [comment] 2024-01-11 17:35
@Innky-Joe please report at https://github.com/nextcloud/related_resources (groupfolders repo might be good as well, but I think it fits better there). But files_automatedtagging  is not relevant in your case.
