### ISSUE TITLE
Can't change "When" condition on NextCloud 18,19 

### ISSUE THREAD

**Issue by Dees7** [nextcloud/files_automatedtagging#263] opened 2020-07-28 16:04 UTC
I have installed app Automated Tagging.
According to this [article ](https://nextcloud.com/blog/nextcloud-flow-makes-it-easy-to-automate-actions-and-workflows/) “when” condition can be changed. But I have only “When file is changed” and no ability to change.

In the Article RED condition “when file is access” has no ability to change too (for example).

### Steps to reproduce
0. Updated from 16. version by version
1. Install app Automated Tagging
2. Go too Settings - Flow
3. add Automated Tagging
4. Can’t change “When” condition

### Expected behaviour
Ability to select When condition

### Actual behaviour
Only "When file is changed" available.

### Server configuration

**Operating system**:
Operating system and version : CentOS Linux release 7.7.1908 (Core)

**PHP version:**
PHP version : PHP 7.2.27

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud version : 18.0.7

**Comment by nickvergessen** [comment] 2020-07-28 16:36
Duplicate of #158

**Closed by nickvergessen** 2020-07-28 16:36 UTC
