### ISSUE TITLE
unexpected folder tagging behavior

### ISSUE THREAD

**Issue by cortex3** [nextcloud/files_automatedtagging#78] opened 2019-08-28 07:39 UTC
### Steps to reproduce
1. assign tag "1day" for rule "File System tag is tagged with 1day-parent"
2. create a folder and assign the "1day-parent" tag
The folder should only have the "1day-parent tag at this point"
3. Add a file to the folder, the file in the folder should now have the "1day" tag as expected
 But so does the directory at this point.

### Expected behaviour
The folder should not receive the "1day" tag after a file is added.

### Actual behaviour
The folder receives the "1day" tag after a file is added.

### Server configuration
**Operating system**: CentOS 7
**Web server:** Nginx 1.12.2
**Database:** MySQL 5.7
**PHP version:** 7.2.19
**Nextcloud version:** 16.0.1
**Where did you install Nextcloud from:** manual
**Signing status:**
```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_accesscontrol: 1.6.0
  - files_antivirus: 2.1.1
  - files_automatedtagging: 1.6.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_retention: 1.5.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - provisioning_api: 1.6.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - socialsharing_email: 1.0.5
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - user_usage_report: 1.1.2
  - workflow_script: 1.1.0
  - workflowengine: 1.6.0

```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** nope

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** FF

**Operating system:** Linux

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment] 2019-08-29 09:06
You could check for the mimetype as well:
Mimetype > is not > `httpd/unix-directory`

**Comment by nickvergessen** [comment] 2019-08-29 09:06
But yeah, updates (which happens here because the mtime changes) also apply tags.

**Comment by nickvergessen** [comment] 2019-08-29 09:09
I'm closing this because it is not a bug but more of a support issue.

**Closed** 2019-08-29 09:08 UTC

**Comment by cortex3** [comment] 2019-08-29 09:29
Oh so it seems like this isn't unexpected behaviour at all. Thanks for your fast help @nickvergessen ! Either way I'm not entirely sure how the automatic deletion workflow is supposed to work here. Checking for the mime type isn't the perfect solution because folders inside of my folder with the parent tag won't be deleted either. Meaning the files might be deleted after my specified time range but I'll be left with a folder containing tons of empty folders.

**Comment by nickvergessen** [comment] 2019-08-29 11:44
There is another problem atm which is preventing folder deletions, or at least making it unexpected:
Folders are "updated" when a file inside is deleted. So if you have 1 day retention, folders are deleted 1 day after the last file inside was deleted.

**Comment by cortex3** [comment] 2019-08-29 13:40
@nickvergessen, So are there any plans to fix both of these issues? The behaviour I was hoping for is that i could tag a folder with the parent tag and no matter what, everything inside that folder is getting deleted after the specified time except of my parent folder. This would imo be the least confusing behaviour for users.

**Comment by nickvergessen** [comment] 2019-08-29 13:59
Unluckily it's quite complex to solve:
https://github.com/nextcloud/server/issues/3572

We are on the way, but still have a long way ahead of us.
